apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argocd-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Thay bằng URL Git repository của bạn trước khi áp dụng manifest này.
    repoURL: https://github.com/HaHust/hello-argoCD.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
