apiVersion: v1
kind: Service
metadata:
  name: hello-argocd
  labels:
    app.kubernetes.io/name: hello-argocd
spec:
  selector:
    app.kubernetes.io/name: hello-argocd
  ports:
    - name: http
      port: 80
      targetPort: http
