apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-dev
resources:
  - ../../base
images:
  - name: ghcr.io/replace-me/hello-argocd
    newName: ghcr.io/hahust/hello-argocd
    newTag: 0ae0660517d0699e9851d047df47fe26aef69fab
